version: '3'
services:
  mysql:
    image: 'mysql:8-oracle'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=dummypassword
      - MYSQL_USER=social-media-user
      - MYSQL_PASSWORD=dummypassword
      - MYSQL_DATABASE=social-media-database
